services:
  postgres:
    image: postgres:15
    container_name: coral-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: coral
    ports:
      - "5432:5432"
    volumes:
      - coral-db-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: coral-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/coral
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: node dist/main

volumes:
  coral-db-data:
